# Generated by Django 4.0.5 on 2022-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='this', editable=False),
            preserve_default=False,
        ),
    ]
