# Generated by Django 4.0.5 on 2022-06-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studym', '0002_topic_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='topic-files/')),
            ],
        ),
    ]
